name: bol
description: "Book Of Life - Your Life's Data in Your Hands."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.8.1

# To automatically upgrade package dependencies:
#
#   flutter pub upgrade --major-versions
#
# To see which dependencies have newer versions available:
#
#   flutter pub outdated
#
# (gjw 20250722)

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
  window_manager: ^0.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
